### ISSUE TITLE
Update webp_jni 

### ISSUE THREAD

**Issue by D01B0EB** [spreadshirt/sprd-webp#1]
Hi,

Tons of thanks for the sprd-webp.

Could you update  webp_jni to newer versions of the libwebp?
So, already were released 0.5.1, 0.5.2 and  0.6.0 with fixes, improvements and etc .

Also my suggestion is to create several libs:  webp050_jni, webp051_jni, webp052_jni, webp060_jni.
It's needs for switch to other version if bugs or unstability will be found.

Thanks!

**Comment by ranSprd** [comment]
upgraded ;-)
